on:
  workflow_dispatch:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: self-hosted
    steps:
      # this was more debug as was curious what came pre-installed
      # GitHub shares this online, e.g. https://github.com/actions/runner-images/blob/macOS-12/20230224.1/images/macos/macos-12-Readme.md
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3
